In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [3]:
df = pd.read_csv('Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
label_encoder_gender = LabelEncoder()
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])

In [8]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [11]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [15]:
one_hot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = one_hot_encoder_geo.fit_transform(df[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
df = pd.concat([df.drop('Geography', axis=1), geo_encoded_df], axis=1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [17]:
X = df.drop('EstimatedSalary', axis=1)
y = df['EstimatedSalary']

In [19]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,0,1.0,0.0,0.0

In [20]:
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
with open('label_encoder_gender_regresssion.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('one_hot_encoder_geo_regresssion.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder_geo, file)

with open('scaler_regresssion.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential  # type: ignore
from tensorflow.keras.layers import Dense  # type: ignore
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard  # type: ignore
import datetime

In [26]:
model = Sequential(
    [
        Dense(
            64,
            activation='relu',
            input_shape = (
                X_train.shape[1],  # HL1 connected with input layer
            )
        ),
        Dense(
            32,
            activation='relu'  # HL2
        ),
        Dense(
            1
        )
    ]
)

model.compile(optimizer="Adam", loss="mean_absolute_error", metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

d:\Code\AI-Bootcamp\Projects\5_Churn_Prediction\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard  # type: ignore
log_dir = "RegressionLogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [28]:
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

In [29]:
history = model.fit(
    X_train,
    y_train,
    validation_data = (
        X_test,
        y_test
    ),
    epochs = 100,
    callbacks = [
        tensorflow_callback,
        early_stopping_callback
    ]
)
history

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100379.6719 - mae: 100379.6719 - val_loss: 98526.7031 - val_mae: 98526.7031
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99675.2734 - mae: 99675.2734 - val_loss: 97115.2891 - val_mae: 97115.2891
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 97221.3281 - mae: 97221.3281 - val_loss: 93524.5156 - val_mae: 93524.5156
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 92398.1250 - mae: 92398.1250 - val_loss: 87528.5078 - val_mae: 87528.5078
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 85320.4375 - mae: 85320.4375 - val_loss: 79612.3594 - val_mae: 79612.3594
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 76827.2969 - mae: 76827.2969 - val_loss: 71048.5781 - val_mae: 71048.5781
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 68273.9219 - mae: 68273.9219 - val_loss: 63326.0898 - val_mae: 63326.0898
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 61032.3633 - mae: 61032.3633 - val_loss: 57389.8594 - val_mae: 57389.8594
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55960.9141 - mae: 55960.9141 - val_loss: 53719.4414 - val_mae: 53719.4414
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52943.8906 - mae: 52943.8906 - val_loss: 51876.3672 - val_mae: 51876.3672
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51487.0859 - mae: 51487.0859 - val_loss: 51216.6992 - val_mae: 51216.6992
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50900.7188 - mae: 50900.7188 - val_loss: 51006.3203 - val_mae: 51006.3203
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50652.3633 - mae: 50652.3633 - val_loss: 50935.8828 - val_mae: 50935.8828
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50515.6484 - mae: 50515.6484 - val_loss: 50881.7891 - val_mae: 50881.7891
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50416.8242 - mae: 50416.8242 - val_loss: 50834.7227 - val_mae: 50834.7227
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50338.3125 - mae: 50338.3125 - val_loss: 50785.3711 - val_mae: 50785.3711
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50269.1797 - mae: 50269.1797 - val_loss: 50748.7031 - val_mae: 50748.7031
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50213.6406 - mae: 50213.6406 - val_loss: 50697.8281 - val_mae: 50697.8281
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50162.3047 - mae: 50162.3047 - val_loss: 50662.4648 - val_mae: 50662.4648
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50115.2930 - mae: 50115.2930 - val_loss: 50617.5312 - val_mae: 50617.5312
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50077.2148 - mae: 50077.2148 - val_loss: 50580.7930 - val_mae: 50580.7930
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50039.9883 - mae: 50039.9883 - val_loss: 50560.2188 - val_mae: 50560.2188
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50002.4102 - mae: 50002.4102 - val_loss: 50530.5039 - val_mae: 50530.5039
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49968.1328 - mae: 49968.1328 - val_loss: 50514.9414 - val_mae: 50514.9414
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49933.7656 - mae: 49933.7656 - val_loss: 50491.4414 - val_mae: 50491.4414
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49904.7891 - mae: 49904.7891 - val_loss: 50470.3516 - val_mae: 50470.3516
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49875.6641 - mae: 49875.6641 - val_loss: 50458.0039 - val_mae: 50458.0039
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49853.4727 - mae: 49853.4727 - val_loss: 50436.8008 - val_mae: 50436.8008
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49832.3594 - mae: 49832.3594 - val_loss: 50423.4414 - val_mae: 50423.4414
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49807.3008 - mae: 49807.3008 - val_loss: 50400.5547 - val_mae: 50400.5547
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49785.3516 - mae: 49785.3516 - val_loss: 50381.1914 - val_mae: 50381.1914
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49767.5898 - mae: 49767.5898 - val_loss: 50369.9883 - val_mae: 50369.9883
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49746.2656 - mae: 49746.2656 - val_loss: 50353.3906 - val_mae: 50353.3906
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49726.7227 - mae: 49726.7227 - val_loss: 50336.8320 - val_mae: 50336.8320
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49713.2578 - mae: 49713.2578 - val_loss: 50322.6289 - val_mae: 50322.6289
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49697.8594 - mae: 49697.8594 - val_loss: 50322.3086 - val_mae: 50322.3086
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49680.7852 - mae: 49680.7852 - val_loss: 50312.0508 - val_mae: 50312.0508
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49665.8008 - mae: 49665.8008 - val_loss: 50311.3242 - val_mae: 50311.3242
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49652.1914 - mae: 49652.1914 - val_loss: 50296.6641 - val_mae: 50296.6641
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49642.2188 - mae: 49642.2188 - val_loss: 50285.1875 - val_mae: 50285.1875
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49632.5938 - mae: 49632.5938 - val_loss: 50290.9570 - val_mae: 50290.9570
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49617.3320 - mae: 49617.3320 - val_loss: 50272.8555 - val_mae: 50272.8555
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49603.1211 - mae: 49603.1211 - val_loss: 50280.2695 - val_mae: 50280.2695
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49595.3047 - mae: 49595.3047 - val_loss: 50263.4023 - val_mae: 50263.4023
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49584.3945 - mae: 49584.3945 - val_loss: 50265.0586 - val_mae: 50265.0586
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49574.9219 - mae: 49574.9219 - val_loss: 50268.1484 - val_mae: 50268.1484
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49566.4766 - mae: 49566.4766 - val_loss: 50251.8984 - val_mae: 50251.8984
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49557.2422 - mae: 49557.2422 - val_loss: 50264.4922 - val_mae: 50264.4922
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49548.9219 - mae: 49548.9219 - val_loss: 50258.6875 - val_mae: 50258.6875
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49540.5664 - mae: 49540.5664 - val_loss: 50256.6289 - val_mae: 50256.6289
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49533.6875 - mae: 49533.6875 - val_loss: 50252.1953 - val_mae: 50252.1953
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49525.7305 - mae: 49525.7305 - val_loss: 50254.5000 - val_mae: 50254.5000
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49518.7539 - mae: 49518.7539 - val_loss: 50249.3047 - val_mae: 50249.3047
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49512.6797 - mae: 49512.6797 - val_loss: 50246.9648 - val_mae: 50246.9648
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49501.9102 - mae: 49501.9102 - val_loss: 50257.6289 - val_mae: 50257.6289
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49495.7852 - mae: 49495.7852 - val_loss: 50254.4258 - val_mae: 50254.4258
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49488.0000 - mae: 49488.0000 - val_loss: 50252.8047 - val_mae: 50252.8047
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49482.9844 - mae: 49482.9844 - val_loss: 50253.8008 - val_mae: 50253.8008
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49477.0352 - mae: 49477.0352 - val_loss: 50256.6094 - val_mae: 50256.6094
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49471.4883 - mae: 49471.4883 - val_loss: 50254.6992 - val_mae: 50254.6992
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49464.5469 - mae: 49464.5469 - val_loss: 50257.9531 - val_mae: 50257.9531
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49458.6641 - mae: 49458.6641 - val_loss: 50266.3242 - val_mae: 50266.3242
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49453.9414 - mae: 49453.9414 - val_loss: 50256.8047 - val_mae: 50256.8047
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49451.3086 - mae: 49451.3086 - val_loss: 50257.4141 - val_mae: 50257.4141
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49442.1758 - mae: 49442.1758 - val_loss: 50263.4805 - val_mae: 50263.4805
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49439.4922 - mae: 49439.4922 - val_loss: 50273.9844 - val_mae: 50273.9844
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49430.3984 - mae: 49430.3984 - val_loss: 50267.8281 - val_mae: 50267.8281
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49426.7617 - mae: 49426.7617 - val_loss: 50286.2734 - val_mae: 50286.2734
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49422.7188 - mae: 49422.7188 - val_loss: 50277.8320 - val_mae: 50277.8320
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49417.8086 - mae: 49417.8086 - val_loss: 50288.2656 - val_mae: 50288.2656
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49411.9258 - mae: 49411.9258 - val_loss: 50279.5703 - val_mae: 50279.5703
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49405.2812 - mae: 49405.2812 - val_loss: 50269.5430 - val_mae: 50269.5430
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49401.9141 - mae: 49401.9141 - val_loss: 50276.0195 - val_mae: 50276.0195
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49401.3906 - mae: 49401.3906 - val_loss: 50271.7461 - val_mae: 50271.7461

In [30]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [32]:
%load_ext tensorboard
%tensorboard --logdir Regressionlogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 5568), started 0:00:49 ago. (Use '!kill 5568' to kill it.)

In [33]:
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE: ', {test_mae})

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50246.9648 - mae: 50246.9648
Test MAE:  {50246.96484375}